### ISSUE TITLE
Bad error when running on fedora

### ISSUE THREAD

**Issue by taftsanders** [taftsanders/satellite-leapp-check#27]
```
↪ ./satellite_leapp_check 

This script is used in determining the availability of the correct repositories for a client for leapp upgrade
This script currently only supports RHEL 7 to 8 upgrade for x86_64 Intel architecture
Satellite is not installed
No satellite package found, assuming this server is a client
❌ RHEL version to leapp to not supplied
- Please use the "-v" option to specify a RHEL version to leapp to
- Example:
  # python satellite_leapp_check.py -c client.example.com -v 8.6 -u admin -p password
Traceback (most recent call last):
  File "satellite_leapp_check.py", line 639, in <module>
  File "satellite_leapp_check.py", line 634, in main
  File "satellite_leapp_check.py", line 535, in check_client
  File "satellite_leapp_check.py", line 137, in get_leapp_version
UnboundLocalError: local variable 'LEAPP_VERSION' referenced before assignment
[279716] Failed to execute script 'satellite_leapp_check' due to unhandled exception!
```

**Comment by taftsanders** [comment]
The initial conduit for executing the script was either the Satellite/Capsule or from the client of the Satellite/Capsule. Changing this to an enhancement as something I would consider adding later on.

**Comment by taftsanders** [comment]
As the executing server would add a lot of variable checks before being able to execute the core function of the project, I will archive this request to save time on more important features.
